'use client';
import {useEffect,useState,useCallback} from 'react';
import {GraduationCap,RefreshCw,Check,Trash2,LogOut} from 'lucide-react';
import {Brand,ReviewWorkspace,api} from '../reviewer';
import type {ReviewResult} from '@/lib/review';
import {Switch} from '@/components/ui/switch';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
type Entry={id:string;studentNumber:number;status:string;createdAt:number;handoff:string;doneIds:string;teacherComment:string};
type Data={room:{name:string;enabled:number};configured:boolean;reviews:Entry[]};
export default function TeacherDashboard({name,needsSetup}:{name:string;needsSetup:boolean}){
 const [setup,setSetup]=useState(needsSetup);const [roomName,setRoomName]=useState('우리 반');const [data,setData]=useState<Data|null>(null);const [current,setCurrent]=useState<ReviewResult|null>(null);const [comment,setComment]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(false);const [filter,setFilter]=useState('all');
 const refresh=useCallback(async()=>{try{setData(await api<Data>('/api/teacher'));setError('')}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{if(setup)return;refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh()},20000);return()=>clearInterval(timer)},[setup,refresh]);
 async function create(){setBusy(true);setError('');try{await api('/api/teacher',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:roomName})});setSetup(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function open(id:string){setBusy(true);setError('');setSaved(false);try{const r=await api<ReviewResult>('/api/reviews/'+id);setCurrent(r);setComment(r.teacherComment||'')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(){if(!current)return;setBusy(true);setError('');try{await api('/api/reviews/'+current.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({teacherComment:comment})});setCurrent({...current,teacherComment:comment});setSaved(true);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(){if(!current)return;setBusy(true);try{await api('/api/reviews/'+current.id,{method:'DELETE'});setCurrent(null);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function toggle(enabled:boolean){setBusy(true);try{await api('/api/teacher',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const rows=data?.reviews.filter(r=>filter==='all'||(filter==='help'?['help','misread'].includes(r.handoff):r.handoff==='ready'&&!r.teacherComment))||[];
 return <div className="app-shell"><header className="topbar"><Brand/><div className="top-actions"><a className="teacher-link" href="/">학생 화면</a><span className="student-pill">선생님</span><a className="icon-button" href="/signout-with-chatgpt?return_to=/" target="_top" aria-label="선생님 로그아웃"><LogOut size={18}/></a></div></header><main className="main-container"><div className="workspace-heading"><div><p className="eyebrow">{name} 선생님</p><h1>학생 제출물 확인</h1></div>{data&&<div className="teacher-status"><label htmlFor="room-open">사진 접수 {data.room.enabled?'열림':'닫힘'}</label><Switch id="room-open" checked={!!data.room.enabled} onCheckedChange={toggle} disabled={busy}/></div>}</div>
 {error&&<p className="error-box" role="alert">{error}</p>}
 {setup?<section className="glass teacher-login"><GraduationCap size={32}/><h2>우리 반 교실 만들기</h2><p>지금 로그인한 계정이 이 교실의 선생님 계정이 됩니다. 학생들은 출석번호만 골라 들어옵니다.</p><label htmlFor="room-name">교실 이름</label><input id="room-name" className="room-name-input" maxLength={50} value={roomName} onChange={e=>setRoomName(e.target.value)}/><button className="primary" disabled={busy||!roomName.trim()} onClick={create}>교실 열기</button></section>:<>
 {!data?.configured&&<div className="setup-notice">실제 사진 피드백을 사용하려면 Google Cloud 연결이 필요합니다. 서비스 계정은 서버 비밀 설정으로만 연결하며, 학생에게 노출되지 않습니다.</div>}
 <div className="teacher-controls"><span className="teacher-summary">{data?.reviews.length||0}개의 글 · {data?.reviews.filter(r=>['help','misread'].includes(r.handoff)).length||0}명의 도움 요청</span><button className="text-button" onClick={refresh} disabled={busy}><RefreshCw size={16}/>새로고침</button></div>
 <div className="teacher-layout"><aside className="glass teacher-sidebar"><h2>{data?.room.name||'우리 반'}</h2><Tabs value={filter} onValueChange={setFilter}><TabsList className="teacher-filters"><TabsTrigger value="all">전체</TabsTrigger><TabsTrigger value="waiting">확인 대기</TabsTrigger><TabsTrigger value="help">도움</TabsTrigger></TabsList></Tabs>{rows.length===0?<p className="muted">아직 해당하는 글이 없어요.</p>:rows.map(r=><button key={r.id} className={'review-row '+(current?.id===r.id?'active':'')} disabled={busy||r.status==='processing'||r.status==='failed'} onClick={()=>open(r.id)}><b>{r.studentNumber}번 학생</b><small>{r.status==='processing'?'사진 읽는 중':r.status==='failed'?'분석 실패 · 다시 올리기 필요':r.teacherComment?'교사 메모 남김':r.handoff==='help'?'도움 요청':r.handoff==='misread'?'글씨 인식 확인 요청':r.handoff==='ready'?'고쳐쓰기 후 확인 대기':r.status==='retake'?'사진·글씨 확인 필요':'첫 피드백 확인 중'}</small><small>{new Date(r.createdAt).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'numeric',minute:'2-digit'})} · {JSON.parse(r.doneIds).length}곳 수정 표시</small></button>)}</aside>
 <div className="teacher-detail">{current?<><div className="teacher-title"><h2>{current.studentNumber}번 학생의 글과 피드백</h2><AlertDialog><AlertDialogTrigger className="icon-button" aria-label="이 글 삭제" disabled={busy}><Trash2 size={18}/></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>이 글과 사진을 삭제할까요?</AlertDialogTitle><AlertDialogDescription>사진, 피드백, 선생님 메모가 함께 삭제되며 되돌릴 수 없습니다.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>취소</AlertDialogCancel><AlertDialogAction onClick={remove}>삭제하기</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div><ReviewWorkspace key={current.id} result={current} teacher/><div className="glass teacher-editor"><label htmlFor="teacher-comment">두 번째 고쳐쓰기 · 선생님 메모</label><textarea id="teacher-comment" maxLength={3000} value={comment} onChange={e=>{setComment(e.target.value);setSaved(false)}} placeholder="종이를 보며 나눈 이야기, 다음에 살펴볼 부분을 남겨주세요."/><button className="primary" disabled={busy} onClick={save}><Check size={17}/>{saved?'저장했어요':'메모 저장'}</button><p className="muted">학생이 자기 피드백 화면을 다시 열면 이 메모도 볼 수 있어요.</p></div></>:<section className="glass empty-teacher"><GraduationCap size={40} style={{margin:'0 auto 15px'}}/><h2>학생의 글을 선택해주세요</h2><p>학생이 본 사진과 피드백을 같은 화면에서 확인해요.</p><p>두 번째 고쳐쓰기는 실제 종이를 보며 함께 진행해주세요.</p></section>}</div></div></>}
 </main></div>;
}
