'use client';
import { useEffect, useRef, useState } from 'react';
import { BookOpen, Camera, Upload, ArrowRight, Check, ChevronLeft, ChevronRight, CircleHelp, GraduationCap, ImagePlus, LoaderCircle, LogOut, Maximize2, PencilLine, RotateCcw, RotateCw, ScanLine, X, ZoomIn, ZoomOut } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { criterionNames, example, qualityMessages, type ReviewResult } from '@/lib/review';

export async function api<T=Record<string,unknown>>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,init);let data:unknown;try{data=await r.json();}catch{throw new Error('잠시 연결이 끊겼어요. 다시 시도해주세요.');}if(!r.ok)throw new Error((data as {error?:string})?.error||'요청을 처리하지 못했어요.');return data as T;}
const json=(data:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
export function Brand(){return <a className="brand" href="/"><span className="brand-icon"><BookOpen size={24}/></span><span>서평 고쳐쓰기</span></a>;}

export default function ReviewerApp(){
 const [number,setNumber]=useState('');const [session,setSession]=useState<{number:number}|null>(null);const [result,setResult]=useState<ReviewResult|null>(null);const [demo,setDemo]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [files,setFiles]=useState<File[]>([]);const [previews,setPreviews]=useState<string[]>([]);const [history,setHistory]=useState<{id:string;createdAt:number;status:string}[]>([]);const [configured,setConfigured]=useState<boolean|null>(null);const input=useRef<HTMLInputElement>(null);const camera=useRef<HTMLInputElement>(null);
 useEffect(()=>{api<{session:{number:number}|null;configured:boolean;reviews:typeof history}>('/api/student').then(d=>{setSession(d.session);setConfigured(d.configured);setHistory(d.reviews)}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{const urls=files.map(f=>URL.createObjectURL(f));setPreviews(urls);return()=>urls.forEach(URL.revokeObjectURL);},[files]);
 async function join(){setError('');setBusy('교실에 들어가고 있어요');try{const d=await api<{number:number}>('/api/student',json({number:Number(number)}));setSession(d);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function signOut(){try{await api('/api/student',{method:'DELETE'});setSession(null);setResult(null);setFiles([]);setHistory([]);setDemo(false)}catch(e){setError((e as Error).message)}}
 function addFiles(list:FileList|null){if(!list||busy)return;setError('');const added=Array.from(list);if(added.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type))){setError('JPG, PNG, WEBP 사진을 골라주세요. HEIC 사진은 JPG로 바꿔주세요.');return;}if(files.length+added.length>4){setError('사진은 한 번에 4장까지 올릴 수 있어요.');return;}if(added.some(f=>f.size>20*1024*1024)){setError('사진 한 장은 20MB 이하로 골라주세요.');return;}setFiles(p=>[...p,...added]);}
 async function rotatePhoto(index:number){const file=files[index];if(!file||busy)return;setError('');setBusy('사진을 돌리고 있어요');try{const rotated=await resize(file,1,'image/png');setFiles(current=>current.map((f,i)=>i===index&&f===file?rotated:f));}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function send(){if(!files.length||!session)return;setBusy('사진을 읽고 고쳐볼 곳을 살펴보고 있어요');setError('');try{const fd=new FormData();for(const f of files)fd.append('photos',await resize(f));const d=await api<ReviewResult>('/api/reviews',{method:'POST',body:fd});setResult(d);setDemo(false);setHistory(h=>[{id:d.id,createdAt:Date.now(),status:d.status},...h]);setFiles([]);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function load(id:string){setError('');setBusy('내 글을 불러오고 있어요');try{setResult(await api<ReviewResult>('/api/reviews/'+id));setDemo(false)}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 return <div className="app-shell"><header className="topbar"><Brand/><div className="top-actions">{session&&<><span className="student-pill">우리 반 · {session.number}번</span><button className="icon-button" onClick={signOut} disabled={!!busy} aria-label="사용 마치기"><LogOut size={18}/></button></>}<a className="teacher-link" href="/teacher"><GraduationCap size={19}/><span>선생님 공간</span></a></div></header>
 <main className="main-container"><div className="workspace-heading"><div><h1>{result?'피드백 확인':'사진 올리기'}</h1></div><ol className="steps" aria-label="활동 순서"><li className={!result?'current':''}><span>1</span>사진 올리기</li><li className={result?'current':''}><span>2</span>종이에 고치기</li><li><span>3</span>선생님 만나기</li></ol></div>
 {error&&<div className="error-box" role="alert">{error}<button onClick={()=>setError('')} aria-label="오류 안내 닫기"><X size={18}/></button></div>}
 {busy&&<div className="busy-banner" role="status"><LoaderCircle className="spin" size={21}/><span>{busy}<small>사진에 따라 1분 정도 걸릴 수 있어요. 이 화면을 열어두세요.</small></span></div>}
 {result?<><div className="result-top"><button className="text-button" onClick={()=>{setResult(null);setDemo(false)}}><ChevronLeft size={18}/>처음 화면</button>{demo&&<span className="demo-badge">체험용 예시 · 실제 분석 결과가 아니에요</span>}</div><ReviewWorkspace key={result.id} result={result} demo={demo} onChange={setResult}/></>:
 <div className="entry-grid"><section className="glass upload-panel"><div className="section-heading"><span className="section-icon"><Camera size={21}/></span><div><h2>종이에 쓴 글을 올려주세요</h2><p>사진은 최대 4장, 글의 순서대로 올려요.</p></div></div>
 {!session&&<div className="join-row"><label htmlFor="student-number">나는</label><Select value={number} onValueChange={setNumber}><SelectTrigger id="student-number" className="number-select"><SelectValue placeholder="출석번호 선택"/></SelectTrigger><SelectContent>{Array.from({length:26},(_,i)=><SelectItem key={i+1} value={String(i+1)}>{i+1}번</SelectItem>)}</SelectContent></Select><button className="primary" disabled={!number||!!busy} onClick={join}>들어가기<ArrowRight size={17}/></button></div>}
 <div className={'dropzone '+(files.length?'has-files':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addFiles(e.dataTransfer.files)}}>
 {files.length?<><p className="photo-direction-hint">글씨가 똑바로 보이나요? 옆으로 누워 있으면 사진을 돌려주세요.</p><div className="photo-grid">{previews.map((src,i)=><div className="photo-upload-item" key={src}><div className="photo-thumb"><img src={src} alt={'올릴 사진 '+(i+1)}/><span>{i+1}쪽</span><button disabled={!!busy} aria-label={(i+1)+'쪽 사진 빼기'} onClick={()=>setFiles(f=>f.filter((_,j)=>j!==i))}><X size={16}/></button></div><button type="button" className="secondary rotate-photo" disabled={!!busy} aria-label={(i+1)+'쪽 사진 오른쪽으로 90도 돌리기'} onClick={()=>rotatePhoto(i)}><RotateCw size={18}/>사진 돌리기</button></div>)}</div></>:<><div className="upload-icon"><ScanLine size={40} strokeWidth={1.4}/></div><h3>서평 사진 촬영</h3><p>종이의 네 모서리와 글 전체가<br/>사진 안에 들어오게 찍어주세요.</p></>}
 <div className="upload-actions"><button className="primary" onClick={()=>camera.current?.click()} disabled={!!busy}><Camera size={19}/>사진 찍기</button><button className="secondary" onClick={()=>input.current?.click()} disabled={!!busy}><Upload size={18}/>사진 선택</button></div>
 <input ref={camera} type="file" accept="image/jpeg,image/png,image/webp" capture="environment" hidden onChange={e=>{addFiles(e.target.files);e.target.value=''}}/><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" multiple hidden onChange={e=>{addFiles(e.target.files);e.target.value=''}}/>
 <small>JPG · PNG · WEBP / 사진을 여기로 끌어와도 돼요</small></div>
 {files.length>0&&<div className="send-row"><span>{files.length}장 준비됐어요{!session?' · 출석번호를 먼저 골라주세요':''}</span><button className="primary" disabled={!session||!!busy||configured===false} onClick={send}>첫 피드백 받기<ArrowRight size={18}/></button></div>}
 {configured===false&&<p className="setup-notice">선생님이 사진 피드백 연결을 준비 중이에요. 지금은 오른쪽의 예시로 사용 방법을 살펴볼 수 있어요.</p>}
 <p className="privacy-note">사진과 피드백은 선생님이 함께 확인해요. 사진 인식과 피드백을 위해 AI 서비스로 전달돼요. 이름 대신 출석번호를 사용해 주세요.</p></section>
 <aside className="entry-aside"><section className="glass how-panel"><h2>사용 방법</h2><div className="how-item"><span>01</span><div><b>사진 올리기</b><p>종이에 쓴 초고를 촬영해주세요.</p></div></div><div className="how-item"><span>02</span><div><b>종이에 고쳐쓰기</b><p>카드에 표시된 부분을 확인하고 고쳐요.</p></div></div><div className="how-item"><span>03</span><div><b>교사 확인받기</b><p>고친 종이를 선생님께 보여주세요.</p></div></div><button className="example-button" onClick={()=>{setResult(structuredClone(example));setDemo(true)}}>예시 보기<ArrowRight size={18}/></button></section>
 {history.length>0&&<section className="glass history-panel"><h2>이 기기에서 올린 내 글</h2>{history.map(h=><button key={h.id} onClick={()=>load(h.id)}><span>{new Date(h.createdAt).toLocaleDateString('ko-KR')}의 서평</span><ChevronRight size={18}/></button>)}</section>}
 </aside></div>}
 </main></div>;
}

export function ReviewWorkspace({result,demo=false,teacher=false,onChange}:{result:ReviewResult;demo?:boolean;teacher?:boolean;onChange?:(r:ReviewResult)=>void}){
 const [active,setActive]=useState(result.feedback.cards[0]?.id||'');const [page,setPage]=useState(0);const [zoom,setZoom]=useState(1);const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [done,setDone]=useState<string[]>(result.doneIds||[]);const [handoff,setHandoff]=useState(result.handoff||'');
 const missingCriteria=result.feedback.criteria.filter(c=>c.status==='missing');
 const allCards=result.feedback.cards;const selected=allCards.find(c=>c.id===active);const lines=result.ocr.lines.filter(l=>l.page===page&&l.box);const figure=useRef<HTMLDivElement>(null);
 useEffect(()=>{setDone(result.doneIds||[]);setHandoff(result.handoff||'')},[result.doneIds,result.handoff]);
 useEffect(()=>{const timer=requestAnimationFrame(()=>{const pane=figure.current;const line=result.ocr.lines.find(l=>selected?.lineIds.includes(l.id)&&l.page===page&&l.box);const paper=pane?.firstElementChild as HTMLElement|null;if(pane&&paper&&line?.box)pane.scrollTo({top:Math.max(0,line.box.y*paper.offsetHeight-pane.clientHeight/2),behavior:'smooth'});});return()=>cancelAnimationFrame(timer)},[active,page,zoom,result.ocr.lines,selected]);
 function select(id:string){setActive(id);const c=allCards.find(x=>x.id===id);const l=result.ocr.lines.find(x=>c?.lineIds.includes(x.id));if(l)setPage(l.page);document.getElementById('feedback-'+id)?.scrollIntoView({behavior:'smooth',block:'nearest'});}
 async function update(nextDone:string[],nextHandoff:string){setError('');if(demo){setDone(nextDone);setHandoff(nextHandoff);return;}setSaving(true);try{await api('/api/reviews/'+result.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({doneIds:nextDone,handoff:nextHandoff})});setDone(nextDone);setHandoff(nextHandoff);onChange?.({...result,doneIds:nextDone,handoff:nextHandoff});}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <div className="review-grid"><section className="glass photo-panel"><div className="photo-toolbar"><div><ImagePlus size={18}/><b>내가 쓴 서평</b></div><div><button className="icon-button" aria-label="사진 축소" onClick={()=>setZoom(z=>Math.max(1,z-.25))} disabled={zoom<=1}><ZoomOut size={19}/></button><span className="zoom-label">{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="사진 확대" onClick={()=>setZoom(z=>Math.min(2,z+.25))} disabled={zoom>=2}><ZoomIn size={19}/></button><button className="icon-button" aria-label="사진 크기 초기화" onClick={()=>setZoom(1)}><Maximize2 size={18}/></button></div></div>
 <div className="photo-scroll" ref={figure}><div className="photo-paper" style={{width:zoom*100+'%'}}><img src={result.pages[page]} alt={(page+1)+'쪽 서평 사진'}/>{lines.map(l=>{const ci=allCards.findIndex(c=>c.lineIds.includes(l.id));if(ci<0||!l.box)return null;const c=allCards[ci];return <button key={l.id} className={'annotation '+(active===c.id?'active ':'')+(c.kind==='spelling'?'spelling':'')} style={{left:l.box.x*100+'%',top:l.box.y*100+'%',width:l.box.w*100+'%',height:l.box.h*100+'%'}} onClick={()=>select(c.id)} aria-label={(ci+1)+'번 피드백 위치: '+l.text}><span>{ci+1}</span></button>})}</div></div>
 <div className="photo-bottom"><span>번호를 누르면 피드백과 연결돼요 · 위치는 인식 결과에 따라 달라질 수 있어요</span>{result.pages.length>1&&<div><button className="icon-button" disabled={page===0} onClick={()=>setPage(p=>p-1)} aria-label="이전 사진"><ChevronLeft size={18}/></button>{page+1} / {result.pages.length}<button className="icon-button" disabled={page===result.pages.length-1} onClick={()=>setPage(p=>p+1)} aria-label="다음 사진"><ChevronRight size={18}/></button></div>}</div>
 </section><section className="feedback-panel"><div className="feedback-heading"><div><p className="eyebrow">첫 번째 고쳐쓰기</p><h2>고쳐볼 부분</h2></div><span className="round-icon"><PencilLine size={23}/></span></div>
 {missingCriteria.length>0&&<section className="glass missing-overview" aria-label="보태야 할 서평 요소"><h3>보태야 할 서평 요소 · {missingCriteria.length}개</h3><ul>{missingCriteria.map(c=><li key={c.name}>{c.name}</li>)}</ul><p>빠진 요소나 까닭을 모두 확인해요. 아래에서는 먼저 보탤 한 가지를 자세히 안내해요.</p></section>}
 <Tabs defaultValue="cards"><TabsList className="feedback-tabs"><TabsTrigger value="cards">고쳐볼 곳 <span>{allCards.length}</span></TabsTrigger><TabsTrigger value="criteria">서평 요소</TabsTrigger></TabsList><TabsContent value="cards"><div className="cards-stack">
 {result.status==='retake'&&<div className="glass quality-card"><ScanLine size={24}/><h3>글씨 인식이 어려워요</h3><p>{qualityMessages[result.ocr.quality]||qualityMessages.uncertain}</p><p className="muted">확실히 읽지 못한 글자는 틀렸다고 판단하지 않았어요.</p></div>}
 {allCards.length===0&&missingCriteria.length===0&&result.status==='ready'&&<div className="glass quality-card"><Check size={27}/><h3>첫 확인을 마쳤어요</h3><p>확실히 고칠 곳은 찾지 못했어요. 글을 소리 내어 읽어보고 선생님과 함께 더 살펴보세요.</p></div>}
 {allCards.map((c,i)=><article id={'feedback-'+c.id} key={c.id} className={'glass feedback-card '+(active===c.id?'selected ':'')+(done.includes(c.id)?'done':'')}><button className="card-select" onClick={()=>select(c.id)} aria-pressed={active===c.id}><span className={'card-number '+c.kind}>{i+1}</span><span><small>{c.kind==='content'?'먼저 보태볼 한 가지':c.kind==='spelling'?'바르게 쓰기':'선생님과 살펴보기'}</small><h3>{c.title}</h3></span>{done.includes(c.id)&&<Check className="done-icon" size={21}/>}</button>{c.quote&&<blockquote>{c.quote}</blockquote>}<p>{c.instruction}</p>{c.correction&&<div className="correction">{c.correction}</div>}{!c.lineIds.length&&<small className="muted">글 전체에서 살펴볼 내용이에요.</small>}{!teacher&&<button className={'done-button '+(done.includes(c.id)?'checked':'')} disabled={saving} onClick={()=>update(done.includes(c.id)?done.filter(id=>id!==c.id):[...done,c.id],handoff)}><Check size={17}/>{done.includes(c.id)?'종이에 고쳤어요':'종이에 고쳤다면 눌러주세요'}</button>}</article>)}
 {error&&<p role="alert" className="error-box">{error}</p>}
 <div className="teacher-handoff glass"><GraduationCap size={23}/><div><h3>{handoff==='ready'?'선생님께 확인을 요청했어요':handoff==='help'?'선생님께 도움을 요청했어요':handoff==='misread'?'글씨 인식 확인을 요청했어요':'교사 확인'}</h3><p>종이에 고친 뒤 선생님께 확인받으세요.</p></div>{!teacher&&!handoff&&<button className="primary" disabled={saving} onClick={()=>update(done,'ready')}>교사 확인 요청<ArrowRight size={17}/></button>}</div>
 {result.teacherComment&&<div className="glass teacher-comment"><h3>선생님의 메모</h3><p>{result.teacherComment}</p></div>}
 {!teacher&&<div className="help-actions"><button disabled={saving} onClick={()=>update(done,'misread')}><RotateCcw size={16}/>제 글을 잘못 읽었어요</button><button disabled={saving} onClick={()=>update(done,'help')}><CircleHelp size={16}/>선생님 도움</button></div>}
 </div></TabsContent><TabsContent value="criteria"><div className="glass criteria-panel"><h3>서평 요소 확인</h3><p>점수가 아니에요. 설명이 있는지 먼저 살폈어요.</p>{result.feedback.criteria.map(c=><div className="criterion" key={c.name}><span>{c.name}</span><b className={c.status}>{c.status==='found'?'찾았어요':c.status==='missing'?'보태봐요':'선생님 확인'}</b></div>)}<div className="criteria-note">제목의 매력, 줄거리의 정확성, 생각과 근거의 연결은 선생님과 함께 살펴요.</div>{teacher&&result.feedback.teacherNotes.map((n,i)=><p key={i} className="teacher-note">{n}</p>)}</div><Dialog><DialogTrigger className="text-button criteria-help">어떤 기준으로 살펴보나요?</DialogTrigger><DialogContent><DialogHeader><DialogTitle>피드백 기준</DialogTitle><DialogDescription>교과서의 다섯 요소와 확실히 읽힌 표기를 살펴요.</DialogDescription></DialogHeader><ul className="rubric-list">{criterionNames.map(n=><li key={n}>{n}</li>)}</ul><p>이유의 타당성이나 표현의 깊이는 평가하지 않아요. 좋은 점과 아쉬운 점을 모두 쓸 필요는 없어요. 추천한다면 누구에게, 왜 추천하는지 살펴요.</p></DialogContent></Dialog></TabsContent></Tabs>
 {selected&&<span className="sr-only" aria-live="polite">선택한 피드백: {selected.title}</span>}</section></div>;
}

async function resize(file:File,quarterTurns=0,type:'image/jpeg'|'image/png'='image/jpeg'):Promise<File>{const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});try{if(bitmap.width*bitmap.height>60000000)throw new Error('사진 해상도가 너무 커요. 더 작은 사진을 선택해주세요.');const ratio=Math.min(1,2200/Math.max(bitmap.width,bitmap.height));const turns=((quarterTurns%4)+4)%4;const width=Math.max(1,Math.round(bitmap.width*ratio)),height=Math.max(1,Math.round(bitmap.height*ratio));const canvas=document.createElement('canvas');canvas.width=turns%2?height:width;canvas.height=turns%2?width:height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('사진을 준비하지 못했어요.');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(turns*Math.PI/2);ctx.drawImage(bitmap,-width/2,-height/2,width,height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('사진을 준비하지 못했어요.')),type,.9));return new File([blob],type==='image/png'?'review.png':'review.jpg',{type});}finally{bitmap.close();}}
